- defaults:
    link:
      create: true
      relink: true

- clean: ['~', '~/.config']

- link:
    ~/.agignore:
    ~/.bash:
    ~/.bash_profile:
    ~/.bashrc:
    ~/.dotfiles: ''
    ~/.gitconfig:
    ~/.cgdb:
    ~/.gitignore_global:
    ~/.haskeline:
    ~/.hgrc:
    ~/.shell:
    # ~/.vimrc:
    ~/.config/lazygit: lazygit
    ~/.config/nvim: nvim
    ~/.config/alacritty: alacritty 
    ~/.vimrc_local:
    ~/.ideavimrc:
    ~/.vsvimrc: vscode/vsvimrc
    ~/.zsh:
    ~/.zshrc:
    ~/.shell_local_before:
    # ~/.zfunctions/prompt_spaceship_setup: zsh/prompt/spaceship-prompt/spaceship.zsh

- create:
  #- ~/.rtorrent/session
  #- ~/.rtorrent/watch
  #- ~/.rtorrent/downloads

- shell:
  - git submodule sync --recursive
  # the following have to run after linking ~/.gitconfig
  - git update-submodules
  - >
    git cleanall -f
    shell/plugins/
    zsh/plugins/
