return {
    {
        "hrsh7th/nvim-cmp",
    },
    {
        'saadparwaiz1/cmp_luasnip',
    },
    {
        'L3MON4D3/LuaSnip',
        dependencies = { "rafamadriz/friendly-snippets" },
    },
    {
        "hrsh7th/cmp-nvim-lsp",
    },
    {
     "quangnguyen30192/cmp-nvim-ultisnips",
    },
    {
        "SirVer/ultisnips"
    },
    {
        "onsails/lspkind-nvim",
    },
    {
        "hrsh7th/cmp-buffer",
    },
    {
        "hrsh7th/cmp-path",
    },
    {
        "hrsh7th/cmp-cmdline",
    },
    {
        "hrsh7th/cmp-vsnip",
    },
    {
        "hrsh7th/vim-vsnip",
    },
}
